$path = "frontend\src\components\ProjectListView.jsx"
$content = [System.IO.File]::ReadAllText($path)
$content = $content.Replace('â‹®â‹®', '⋮⋮')
$content = $content.Replace('âœ ï¸ ', '✏️')
$content = $content.Replace('âœ•', '✕')
$content = $content.Replace('ğŸ‘¥', '👥')
$content = $content.Replace('âŠ–', '⊖')
$content = $content.Replace('â†‘', '↑')
$content = $content.Replace('â†“', '↓')
$content = $content.Replace('â–¼', '▼')
$content = $content.Replace('â–¶', '▶')
$content = $content.Replace('â†³', '↳')
$content = $content.Replace('ğŸ“…', '📅')
$content = $content.Replace('ğŸ‘¤', '👤')
$content = $content.Replace('ğŸ”—', '🔗')
$content = $content.Replace('Æ’', 'ƒ')
$content = $content.Replace('ğŸ†”', '🆔')
$content = $content.Replace('â ±ï¸ ', '⏱️')
$content = $content.Replace('ğŸ” ', '🔍')
$content = $content.Replace('âœ…', '✅')

[System.IO.File]::WriteAllText($path, $content, [System.Text.Encoding]::UTF8)
